version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api_server

  api_server:
    build: .
    ports:
      - "3000:3000"
